export const EDIT_EXAM = "EDIT_EXAM";
export const SELECT_QUESTIONS = "SELECT_QUESTIONS";
export const CLOSE_SELECT_QUESTIONS = "CLOSE_SELECT_QUESTIONS";
export const AVAILABLE_QUESTIONS = "AVAILABLE_QUESTIONS";

export const CREATE_EXAM_MODAL = "CREATE_EXAM_MODAL";
export const CLOSE_CREATE_EXAM_MODAL = "CLOSE_CREATE_EXAM_MODAL";
