export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const FETCH_ALL_EXAMS_REQUEST = "FETCH_ALL_EXAMS_REQUEST";
export const FETCH_ALL_EXAMS_SUCCESS = "FETCH_ALL_EXAMS_SUCCESS";

export const FETCH_PAST_EXAMS_REQUEST = "FETCH_PAST_EXAMS_REQUEST";
export const FETCH_PAST_EXAMS_SUCCESS = "FETCH_PAST_EXAMS_SUCCESS";

export const FETCH_AVAILABLE_EXAMS_REQUEST = "FETCH_AVAILABLE_EXAMS_REQUEST";
export const FETCH_AVAILABLE_EXAMS_SUCCESS = "FETCH_AVAILABLE_EXAMS_SUCCESS";

export const START_EXAM_REQUEST = "START_EXAM_REQUEST";
export const START_EXAM_SUCCESS = "START_EXAM_SUCCESS";

export const FETCH_QUESTION_REQUEST = "FETCH_QUESTION_REQUEST";
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS";

export const SUBMIT_EXAM_REQUEST = "SUBMIT_EXAM_REQUEST";
export const SUBMIT_EXAM_SUCCESS = "SUBMIT_EXAM_SUCCESS";

export const GRADE_SUBMISSION_REQUEST = "GRADE_SUBMISSION_REQUEST";
export const GRADE_SUBMISSION_SUCCESS = "GRADE_SUBMISSION_SUCCESS";
